version: 1.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release
platform: Any CPU

clone_depth: 1

services: 
- mongodb

before_build:
- ps: dotnet restore


build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: quiet

artifacts:
- path: '*.nupkg'
  name: Nuget

deploy:
- provider: NuGet
  api_key:
    secure: wDpncF7Nunu2WyL9m0qqElo44vmFxyD4qhOvXkyBhThZjEtG4mEtsfzzl01zoTec
  on:
    branch: master